### ISSUE TITLE
Translations master issue

### ISSUE THREAD

**Issue by Pabszito** [ComuGamersES/arenapvp-issue-tracker#2]
- [ ] Incorrect The Bridge `¡Player scored!` title format

![image](https://github.com/ComuGamersES/arenapvp-issue-tracker/assets/37744843/8535843f-b890-407e-8384-08325c85fc86)

- [ ] Missing `(s)` ending on round start countdown message

![image](https://github.com/ComuGamersES/arenapvp-issue-tracker/assets/37744843/caa968e6-bb23-4ab5-bfd6-2afb6c4449ac)

- [ ] Missing The Bridge kill message translations

![image](https://github.com/ComuGamersES/arenapvp-issue-tracker/assets/37744843/5c06b50d-813b-454a-b519-ef01cec399d7)

- [ ] Hardcoded messages for the Kit Editor menu, requires plugin author support

![image](https://github.com/ComuGamersES/arenapvp-issue-tracker/assets/37744843/62f6fd11-38c2-42a8-a1fa-50ef19261f6b)

- [ ] Missing rank on party scoreboard

![image](https://github.com/ComuGamersES/arenapvp-issue-tracker/assets/37744843/ae09ba33-ccb8-4df2-8a9f-7fe38a2a5643)

- [ ] Missing color reset on rank up broadcast (`!` should be white)

![image](https://github.com/ComuGamersES/arenapvp-issue-tracker/assets/37744843/3e089842-5ef0-4962-ac13-a0e9d6c6f174)
